--------------------------------------------------------
--  File created - Sunday-January-06-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table NURSES
--------------------------------------------------------

  CREATE TABLE "HR"."NURSES" 
   (	"NURSEID" NUMBER(*,0), 
	"NURSENAME" VARCHAR2(20 BYTE), 
	"NURSESURNAME" VARCHAR2(20 BYTE), 
	"NURSEEXPERIMENT" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.NURSES
SET DEFINE OFF;
Insert into HR.NURSES (NURSEID,NURSENAME,NURSESURNAME,NURSEEXPERIMENT) values (18,'güner','caglayan',14);
Insert into HR.NURSES (NURSEID,NURSENAME,NURSESURNAME,NURSEEXPERIMENT) values (12,'orhun','selen',12);
Insert into HR.NURSES (NURSEID,NURSENAME,NURSESURNAME,NURSEEXPERIMENT) values (29,'selin ','sagir',12);
Insert into HR.NURSES (NURSEID,NURSENAME,NURSESURNAME,NURSEEXPERIMENT) values (26,'sena ','sakalli',24);
Insert into HR.NURSES (NURSEID,NURSENAME,NURSESURNAME,NURSEEXPERIMENT) values (32,'ece ','takur',24);
Insert into HR.NURSES (NURSEID,NURSENAME,NURSESURNAME,NURSEEXPERIMENT) values (23,'mete','cetinkaya',14);
Insert into HR.NURSES (NURSEID,NURSENAME,NURSESURNAME,NURSEEXPERIMENT) values (1,'meri','mauro',15);
--------------------------------------------------------
--  DDL for Index NURSE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."NURSE_PK" ON "HR"."NURSES" ("NURSEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table NURSES
--------------------------------------------------------

  ALTER TABLE "HR"."NURSES" ADD CONSTRAINT "NURSE_PK" PRIMARY KEY ("NURSEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."NURSES" MODIFY ("NURSEID" NOT NULL ENABLE);
