--------------------------------------------------------
--  File created - Sunday-January-06-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PATIENTS
--------------------------------------------------------

  CREATE TABLE "HR"."PATIENTS" 
   (	"PATIENTID" NUMBER(*,0), 
	"PATIENTNAME" VARCHAR2(20 BYTE), 
	"PATIENTSURNAME" VARCHAR2(20 BYTE), 
	"PATIENTAGE" NUMBER(*,0), 
	"PATIENTGENDER" VARCHAR2(20 BYTE), 
	"PATIENTDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.PATIENTS
SET DEFINE OFF;
Insert into HR.PATIENTS (PATIENTID,PATIENTNAME,PATIENTSURNAME,PATIENTAGE,PATIENTGENDER,PATIENTDATE) values (12,'rasim','demiral',21,'man',to_date('16-JAN-19','DD-MON-RR'));
Insert into HR.PATIENTS (PATIENTID,PATIENTNAME,PATIENTSURNAME,PATIENTAGE,PATIENTGENDER,PATIENTDATE) values (4,'seyit','evren',22,'women',to_date('17-JAN-19','DD-MON-RR'));
Insert into HR.PATIENTS (PATIENTID,PATIENTNAME,PATIENTSURNAME,PATIENTAGE,PATIENTGENDER,PATIENTDATE) values (28,'oguz','bayrak',23,'man',to_date('30-JAN-19','DD-MON-RR'));
Insert into HR.PATIENTS (PATIENTID,PATIENTNAME,PATIENTSURNAME,PATIENTAGE,PATIENTGENDER,PATIENTDATE) values (88,'enver','bayram',31,'man',to_date('15-JAN-19','DD-MON-RR'));
Insert into HR.PATIENTS (PATIENTID,PATIENTNAME,PATIENTSURNAME,PATIENTAGE,PATIENTGENDER,PATIENTDATE) values (97,'aleyna','abaci',24,'women ',to_date('22-JAN-19','DD-MON-RR'));
Insert into HR.PATIENTS (PATIENTID,PATIENTNAME,PATIENTSURNAME,PATIENTAGE,PATIENTGENDER,PATIENTDATE) values (1,'eren','kutbay',24,'man',to_date('06-FEB-19','DD-MON-RR'));
Insert into HR.PATIENTS (PATIENTID,PATIENTNAME,PATIENTSURNAME,PATIENTAGE,PATIENTGENDER,PATIENTDATE) values (2,'metin','demiral',22,'man',to_date('30-JAN-19','DD-MON-RR'));
Insert into HR.PATIENTS (PATIENTID,PATIENTNAME,PATIENTSURNAME,PATIENTAGE,PATIENTGENDER,PATIENTDATE) values (6,'mehmet','duman',23,'man',to_date('29-JAN-19','DD-MON-RR'));
Insert into HR.PATIENTS (PATIENTID,PATIENTNAME,PATIENTSURNAME,PATIENTAGE,PATIENTGENDER,PATIENTDATE) values (69,'ercan','cakir',45,'man',to_date('20-FEB-19','DD-MON-RR'));
Insert into HR.PATIENTS (PATIENTID,PATIENTNAME,PATIENTSURNAME,PATIENTAGE,PATIENTGENDER,PATIENTDATE) values (96,'selin','oguz',21,'women',to_date('25-JAN-19','DD-MON-RR'));
Insert into HR.PATIENTS (PATIENTID,PATIENTNAME,PATIENTSURNAME,PATIENTAGE,PATIENTGENDER,PATIENTDATE) values (8,'murat','gercek',23,'women',to_date('29-JAN-19','DD-MON-RR'));
Insert into HR.PATIENTS (PATIENTID,PATIENTNAME,PATIENTSURNAME,PATIENTAGE,PATIENTGENDER,PATIENTDATE) values (75,'muhammed','ajuri',22,'man',to_date('30-JAN-19','DD-MON-RR'));
Insert into HR.PATIENTS (PATIENTID,PATIENTNAME,PATIENTSURNAME,PATIENTAGE,PATIENTGENDER,PATIENTDATE) values (34,'ersin','güreli',28,'man',to_date('12-FEB-19','DD-MON-RR'));
Insert into HR.PATIENTS (PATIENTID,PATIENTNAME,PATIENTSURNAME,PATIENTAGE,PATIENTGENDER,PATIENTDATE) values (39,'terry','duraccio',23,'women ',to_date('31-JAN-19','DD-MON-RR'));
--------------------------------------------------------
--  DDL for Index PATIENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."PATIENTS_PK" ON "HR"."PATIENTS" ("PATIENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PATIENTS
--------------------------------------------------------

  ALTER TABLE "HR"."PATIENTS" ADD CONSTRAINT "PATIENTS_PK" PRIMARY KEY ("PATIENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."PATIENTS" MODIFY ("PATIENTID" NOT NULL ENABLE);
